<?php
$installer = $this;
$installer->startSetup();
$sql=<<<SQLTEXT
TRUNCATE TABLE order_button;
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (1,'Confirm',NULL,NULL,'go','ChangeStatusForView','Administrators,Customers Support,CS Supervisor,Tracking Advisor,Gulf,CS Manager,Sales Representative ,Sales Manager','pending,retention','confirmed',NULL,NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (2,'At Hub',NULL,NULL,'go','ChangeStatusForView','Administrators,Customers Support,CS Supervisor,Tracking Advisor,Gulf,CS Manager,Sales Representative ,Sales Manager','waiting_on_stock','at_hub',NULL,NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (3,'In Process',NULL,NULL,'save','ChangeStatusForView','Administrators,Storekeepers','confirmed','in_process',NULL,NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (4,'Back To Stock',NULL,NULL,'delete','ChangeStatusForView','Administrators,Storekeepers','refusal_shipment_ready','back_to_stock',NULL,NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (5,'Pending Return',NULL,NULL,'delete','ChangeStatusForView','Administrators,Operators','at_hub,cancel_request,int_at_hub,waiting_on_stock','pending_return',NULL,NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (6,'Waiting On Stock',NULL,NULL,'delete','ChangeStatusForView','Administrators,Operators','at_hub,int_at_hub','waiting_on_stock',NULL,NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (7,'Pending Refusal Return',NULL,NULL,'delete','ChangeStatusForView','Administrators,Operators','customer_rejected,delayed_shipment,final_rejection,out_for_delivery,resend_to_customer,second_out_for_delivery','pending_refusal_return',NULL,NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (8,'Refusal Shipment In Process',NULL,NULL,'delete','ChangeStatusForView','Administrators,Operators','pending_refusal_return','refusal_shipment_process',NULL,NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (9,'Second Out For Delivery',NULL,NULL,'delete','ChangeStatusForView','Administrators,Operators','resend_to_customer','second_out_for_delivery',NULL,NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (10,'Delivered',NULL,NULL,'save','ChangeStatusForView','Administrators,Accountant,CFO,Tracking Advisor','customer_rejected,delayed_shipment,final_rejection,out_for_delivery,pending_refusal_return,resend_to_customer,second_out_for_delivery','pending_aramex_payment',NULL,NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (11,'Pending Refusal Return',NULL,NULL,'delete','ChangeStatusForView','Administrators,Accountant,CFO,Tracking Advisor','customer_rejected,delayed_shipment,final_rejection,out_for_delivery,pending_aramex_payment,resend_to_customer,second_out_for_delivery','pending_refusal_return',NULL,NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (12,'Complete',NULL,NULL,'save','ChangeStatusForView','Administrators,Storekeepers,Accountant,CFO','paid,pending_cfo_approval,pos','complete',NULL,NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (13,'Paid',NULL,NULL,'save','ChangeStatusForView','Administrators,Accountant,CFO','cash','complete',NULL,NULL,'0','0',NULL);

INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (14,'Process Orders',NULL,NULL,'go','ChangeStatusForGrid','Administrators,Storekeepers,China Operation','confirmed','in_process',NULL,NULL,'1','1',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (15,'Return Received',NULL,NULL,'back','ChangeStatusForGrid','Storekeepers','ready_to_return','return_canceled',NULL,NULL,'0','0',NULL);

INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (16,'Refusal Ready To Return',NULL,NULL,'back','GenerateReport&ChangeStatusForGrid','Administrators,Operators,China Operation','refusal_shipment_process','refusal_shipment_ready','{\"report_type\":\"Stock In - Refusal\",\"report_title\":\"Stock In - Refusal Report\"}',NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (17,'Ready to return',NULL,NULL,'back','GenerateReport&ChangeStatusForGrid','Operators','pending_return','ready_to_return','{\"report_type\":\"Stock In - Return\",\"report_title\":\"Stock In - Return Report\"}',NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (18,'Eg Ready For Hub',NULL,NULL,'save','GenerateReport&ChangeStatusForGrid','Storekeepers','in_process','ready_for_hub','{\"report_type\":\"Stock In\",\"report_title\":\"Eg Orders Report\"}',NULL,'1','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (19,'Int Ready For Hub',NULL,NULL,'save','GenerateReport&ChangeStatusForGrid','China Operation','in_process','int_ready_for_hub','{\"report_type\":\"Stock In\",\"report_title\":\"Int Orders Report\"}',NULL,'1','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (20,'Eg Paid Ready For Hub',NULL,NULL,'save','GenerateReport&ChangeStatusForGrid','Storekeepers','processing','paid_ready_for_hub','{\"report_type\":\"Stock In\",\"report_title\":\"Eg Orders Report\"}',NULL,'1','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (21,'Int Paid Ready For Hub',NULL,NULL,'save','GenerateReport&ChangeStatusForGrid','China Operation','processing','paid_int_ready_for_hub','{\"report_type\":\"Stock In\",\"report_title\":\"Int Orders Report\"}',NULL,'1','0',NULL);

INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (22,'International Orders',NULL,NULL,'add','GenerateReportForGrid','Administrators,Operators','paid_int_at_hub',NULL,'{\"report_type\":\"Stock In\",\"report_title\":\"International Orders\"}',NULL,'1','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (23,'At Hub Orders',NULL,NULL,'add','GenerateReportForGrid','Administrators,Operators','at_hub,int_at_hub,paid_at_hub',NULL,'{\"report_type\":\"Stock In\",\"report_title\":\"At Hub, Paid At Hub & Int At Hub Orders\"}',NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (24,'Holded Report',NULL,NULL,'add','GenerateReportForGrid','Operators','holded',NULL,'{\"report_type\":\"Stock In\",\"report_title\":\"Holded Report\"}',NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (25,'Waiting On Stock Report',NULL,NULL,'add','GenerateReportForGrid','Operators','waiting_on_stock',NULL,'{\"report_type\":\"Stock In\",\"report_title\":\"Waiting On Stock Report\"}',NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (26,'Return Report',NULL,NULL,'add','GenerateReportForGrid','Operators','pending_return',NULL,'{\"report_type\":\"Stock In\",\"report_title\":\"Return Report\"}',NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (27,'Eg Orders Report',NULL,NULL,'add','GenerateReportForGrid','Administrators,Storekeepers','in_process,processing',NULL,'{\"report_type\":\"Stock In\",\"report_title\":\"In Process & Processing Report\"}',NULL,'1','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (28,'Confirmed Report',NULL,NULL,'add','GenerateReportForGrid','Operators','confirmed',NULL,'{\"report_type\":\"Stock In\",\"report_title\":\"Confirmed Report\"}',NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (29,'Received Report',NULL,NULL,'save','GenerateReportForGrid','Administrators,Operators,China Operation','int_ready_for_hub,paid_int_ready_for_hub,paid_ready_for_hub,ready_for_hub',NULL,'{\"report_type\":\"Stock In\",\"report_title\":\"For Hub Report\"}',NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (30,'Pending Report',NULL,NULL,'add','GenerateReportForGrid','Operators','pending',NULL,'{\"report_type\":\"Stock Take\",\"report_title\":\"Pending Report\"}',NULL,'0','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (31,'Int Stock Take',NULL,NULL,'save','GenerateReportForGrid','China Operation','int_ready_for_hub,paid_int_ready_for_hub',NULL,'{\"report_type\":\"Stock Take\",\"report_title\":\"Int Stock Take Report\"}',NULL,'1','0',NULL);
INSERT INTO `order_button` (`id`,`name`,`color`,`icon`,`css_classes`,`action_type`,`accepted_role`,`order_current_status`,`order_tobe_status`,`report_attrs`,`order_removed_buttons`,`check_warehouse`,`check_delivery_date`,`check_opening_tickets`) VALUES (32,'Eg Stock Take',NULL,NULL,'save','GenerateReportForGrid','Storekeepers','paid_ready_for_hub,ready_for_hub',NULL,'{\"report_type\":\"Stock Take\",\"report_title\":\"Eg Stock Take Report\"}',NULL,'1','0',NULL);

SQLTEXT;

$installer->run($sql);
//demo 
//Mage::getModel('core/url_rewrite')->setId(null);
//demo 
$installer->endSetup();
	 